#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q standard 
#PBS -l select=1000:ncpus=36:mpiprocs=36
#PBS -l min_walltime=001:00:00
#PBS -l max_walltime=024:00:00
#PBS -l     walltime=024:00:00
#PBS -j oe
#PBS -V

echo ''
echo 'start: '$(date)

source ${myGit}/bash/pbs/pbs_pulse

echo ''
echo 'ulimit -a'
ulimit -a

echo ''
echo 'module list pre-purge:'
module list

echo ''
echo 'module purge'
module purge

echo ''
echo 'module list post-purge:'
module list

source ${myGit}'bash/machines/'${host_name}'/load_fortran' 

echo ''
echo 'module list'
module list

echo ''
echo 'export fortran_compiler_mpi_gnu=ftn'
export fortran_compiler_mpi_gnu='mpif90'

# copy files to $WORKDIR and compile there
source ${myGit}bash/pbs/pbs_copier

echo ''
echo 'make debug:'
make debug

echo ''
echo 'make:'
make

echo ''
echo 'make clean:'
make clean

echo ''
echo 'directory = '$(pwd)

echo ''
echo 'ls -alh:'
ls -alh

export iam=topaz-edison-pbs

echo ''
echo '* * * cat '${iam}
echo ''

cat ${iam}

echo ''
echo '* * *'
echo ''

echo ''
echo ${run}' ./makesAC < inm1a.1'
${run} ./makesAC < inm1a.1

echo ''
echo 'make clean'
make clean

echo ''
echo 'finish: '$(date)
echo ''

